version: '3.5'

#Networking (docker networks)
networks:
  pool_pool-network-dev:
    external: true

#Templates
x-pool-network-dev:
  &pool-network-dev
  networks:
  - pool_pool-network-dev

#Containers
services:
  proxy:
    <<: *pool-network-dev
    image: registry.tor.ph/hiveon/proxy:${PROXY_BUILD_NUMBER:-latest}
    container_name: proxy
    hostname: proxy
    ports:
      - "8000:8000"
      - "8099:8090"
    external_links:
      - idp:idp
      - hydra:hydra
      - hadmin:hadmin
      - hapi:hapi
      - influx:influx
      - hasbin:hasbin
      - portal:portal
      
  nginx:
    <<: *pool-network-dev
    container_name: nginx
    hostname: nginx
    image: nginx
    volumes:
      - ./devops/nginx/conf.d:/etc/nginx/conf.d
      - ./devops/nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    external_links:
      - idp:idp
      - hydra:hydra
      - hadmin:hadmin
      - hapi:hapi
      - influx:influx
      - hasbin:hasbin
      - portal:portal

  portal:
    <<: *pool-network-dev
    image: registry.tor.ph/hiveon/portal:${PORTAL_BUILD_NUMBER:-latest}
    container_name: portal
    hostname: proxy
    ports:
      - 8083:8080
    external_links:
      - hapi:hapi
      - hadmin:hadmin
      - hydra:hydra
      - idp:idp