hydra:
  admin: "http://localhost:4445"
  api: "http://localhost:4444"  
  docker: hydra

sequelize2:
  host: hiveos-eth-prod.cyzben5dhs1h.eu-central-1.rds.amazonaws.com
  port: 3306
  name: hiveos_eth
  user: hiveos_eth_ro
  sslmode: false
  password: 7C9RAXMGQKiOKZ1A

sequelize3:
  host: rm-2zefa4845bwys9fb9io.mysql.rds.aliyuncs.com
  port: 3306
  name: block
  user: ethscan_read
  password: OLyEwNnx75uWtGkI
  sslmode: false

influx:
  host: "10.100.100.10"
  port: 8086
  name: "minerdash"
  user: "admin"
  password: "UadZOn2Hsy1Dyt07"

idp:
  port: 3000
  host: "id.hiveon.localhost"
  client_id: "idp"
  client_secret: "idp-secret"
  callback: "https://id.hiveon.local:3000/callback"
  db:
    host: "10.100.100.2"
    port: "5432"
    name: "idp"
    user: "idp"
    sslmode: false
    password: "8GWbz2JF4FMe1Q8X"

portal:
  port: 8080
  host: "0.0.0.0"
  callback: "https://hiveon.local:8080"
  client_id: "portal"
  client_secret: "portal-secret"

api:
  port: 8090
  host: "0.0.0.0"

admin:
  port: 3002
  host: "0.0.0.0"
  client_id: "admin"
  client_secret: "admin-secret"    
  callback: "localhost:3002/callback"
  db:
    host: "10.100.100.2"
    port: 5432
    name: "idp"
    user: "idp"
    sslmode: false
    password: "8GWbz2JF4FMe1Q8X"

auth:
  sign_key: "Th1s!sMyR4Nd0MStri4gPleaseChangeIt"

security:
  publicURL:  "/api/miner"
  securedURL: "/api/private"
  useCasbin: false

mail:
  active: "true"
  smtp: "smtp.gmail.com"
  port: 465
  user: "hiveonid"
  password: "Hiveon!23"
  from: "id@hiveon.net"

redis:
  host: "localhost"
  port: 6379
  db: 1
  password: ""

remember_for: 360000

app:
  config:
    pool:
      workerState: 20m
      pgOneDay: "26 hour"
      poolZoom: "25h"
      hashrate:
        hashrateCul: 4000000000
        hashrateCulDivider: 1200
ZOOM_CONFIG:
  d:
    time: "25h"
    zoom: "20m"

WORKER_STAT_CONFIG:
  d:
    time: "25h"
    zoom: "5m"
    workerOfflineMin: 1m
  defaultPercentage: 0.03

pool:
  workers_api: "http://localhost:8090/api/private/statistic/workers"
  mapping_api: "http://localhost:8090/api/private/statistic/mapping"
  idp_api: "http://localhost:3000/api"

kafka:
  brokers: "ec2-18-197-235-102.eu-central-1.compute.amazonaws.com:9092, ec2-18-197-240-139.eu-central-1.compute.amazonaws.com:9092,ec2-18-194-140-186.eu-central-1.compute.amazonaws.com:9092"
  ca_location: "./internal/consumer/kafka/ca-cert"
  username: "hiveos_eth_web_prod"
  password: "YX7pfF3JrXACd6GK"
  topics: "hiveos_eth_stats_prod2 hiveos_eth_stats_prod hiveos_eth_exchange_prod"
  group_id: "hiveos_new_eu_web_prod"
  retention: "two_hours"
  db_name: "minerdash"
  precision: "n"
  mining_pools: "helsinki-pool hiveos-de-node-1 hiveos-de-node-2 sparkpool-us-node-01 sparkpool-us-node-02"

telegrambot:
  token: "789227906:AAFwe3FJvXUoO61JRg2kg-_s4VweQ7_HRv0"
  chatID: -316538651

scheduler:
  eth_API:   "https://www.etherchain.org/api/basic_stats"
  cny_API: "https://api.coinmarketcap.com/v1/ticker/ethereum/?convert=CNY"
  retention: "a_year"
  measurement: "eth_stats"